OCPBUGS-28965: update textlogger usage
openshift/machine-api-provider-ibmcloud pull request #35
Opened 2024-02-07 21:14 UTC by elmiko

This change adds the configuration and command line flags setup for the textlogger configuration. It is being added to address an error when botting with the current code, that was changed to an updated klogr during the kubernetes 1.29 update. The configuration code is inspired by the machine-api-provider-vsphere main function.

2024-02-07 21:22 UTC, elmiko commented
/jira refresh

2024-02-08 09:55 UTC, JoelSpeed commented on cmd/manager/main.go
>  	klog.InitFlags(nil)
This line must be removed now, we don't need these klog flags anymore

2024-02-08 13:34 UTC, elmiko commented
updated with Joel's suggestion

2024-02-08 15:33 UTC, cjschaef requested changes
Looks like a flag isn't supported.

If it would help, I could attempt to build some custom images and releases to iron out these log change kinks.

2024-02-08 15:33 UTC, cjschaef commented on cmd/manager/main.go
>  	flag.Set("logtostderr", "true")
Looks like this needs to be removed based on the latest `e2e-ibmcloud` build
```
flag provided but not defined: -logtostderr
Usage of /machine-controller-manager:
  -health-addr string
    	The address for health checking. (default ":9440")
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -leader-elect
    	Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability.
  -leader-elect-lease-duration duration
    	The duration that non-leader candidates will wait after observing a leadership renewal until attempting to acquire leadership of a led but unrenewed leader slot. This is effectively the maximum duration that a leader can be stopped before it is replaced by another candidate. This is only applicable if leader election is enabled. (default 2m0s)
  -leader-elect-resource-namespace string
    	The namespace of resource object that is used for locking during leader election. If unspecified and running in cluster, defaults to the service account namespace for the controller. Required for leader-election outside of a cluster.
  -metrics-bind-address string
    	Address for hosting metrics (default ":8081")
  -namespace string
    	Namespace that the controller watches to reconcile machine-api objects. If unspecified, the controller watches for machine-api objects across all namespaces.
  -v value
    	number for the log level verbosity of the testing logger
  -version
    	print version and exit
  -vmodule value
    	comma-separated list of pattern=N log level settings for files matching the patterns
```

2024-02-08 16:53 UTC, MayXuQQ commented
pre-merge test with [e8aed223](https://storage.googleapis.com/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1755594040155312128/build-log.txt)

> $  oc get po -n openshift-machine-api    
NAME                                                 READY   STATUS             RESTARTS       AGE
cluster-autoscaler-operator-6c4f8f7cd6-szgx2         2/2     Running            0              72m
cluster-baremetal-operator-544f778588-wb5jt          2/2     Running            0              72m
control-plane-machine-set-operator-89cc757b4-4qjx2   1/1     Running            0              72m
machine-api-controllers-5c7b86795d-xjr4g             6/7     CrashLoopBackOff   17 (70s ago)   64m
machine-api-operator-6c548cfd5f-vtvdg                2/2     Running            0              71m

> $ oc logs -n openshift-machine-api  -c  machine-controller  machine-api-controllers-5c7b86795d-xjr4g
flag provided but not defined: -logtostderr
Usage of /machine-controller-manager:
  -health-addr string
...

2024-02-09 13:31 UTC, elmiko commented
@cjschaef happy for any help, and i thought i did remove that line in the latest version but seems like we still have a problem.

2024-02-09 13:35 UTC, elmiko commented on cmd/manager/main.go
>  	flag.Set("logtostderr", "true")
i think this line is causing the issue, not sure if it needs to happen after the textlogger init or if we need to add an option.

2024-02-09 13:37 UTC, elmiko commented
updated to set the logtostderr in a similar manner as the [vsphere code](https://github.com/openshift/machine-api-operator/blob/master/cmd/vsphere/main.go#L94)

2024-02-09 15:41 UTC, cjschaef commented
Do we need to add the flag to the binary in order to support that klog option? Since it appears to be the same error yet.
https://github.com/openshift/machine-api-operator/blob/8d0f4a1ea47f92c2e78273c24f549202f1ae8178/cmd/vsphere/main.go#L80-L84

I can try testing that out today, and some other tweaks if necessary to see what I find out.

2024-02-09 23:10 UTC, cjschaef commented
I did some local testing and used a custom release and this appears to work properly
```
diff --git a/cmd/manager/main.go b/cmd/manager/main.go
index a5317135..34934a8c 100644
--- a/cmd/manager/main.go
+++ b/cmd/manager/main.go
@@ -90,11 +90,20 @@ func main() {
                "Address for hosting metrics",
        )
 
+       logToStderr := flag.Bool(
+               "logtostderr",
+               true,
+               "Log to Stderr instead of files",
+       )
+
        textLoggerConfig := textlogger.NewConfig()
        textLoggerConfig.AddFlags(flag.CommandLine)
        ctrl.SetLogger(textlogger.NewLogger(textLoggerConfig))
-       klog.LogToStderr(true)
+
        flag.Parse()
+       if logToStderr != nil {
+               klog.LogToStderr(*logToStderr)
+       }
 
        if *printVersion {
                fmt.Println(version.String)
```

Here's the commit I added on top of this PR (if that is easier to see diffs):
https://github.com/cjschaef/machine-api-provider-ibmcloud/commit/28bdf2551e0d242748f8e473d1bd5ba7161c79f8
```
machine-api-controllers-5749bdff54-5r5pp              7/7     Running   0          5m19s
```


```
machine-api                                4.16.0-0.nightly-2024-02-08-073857   True        False         False      3m42s
```

2024-02-10 04:19 UTC, elmiko commented
added @cjschaef 's commit into mine, i squashed for brevity but added co-author reference =)

2024-02-12 10:02 UTC, JoelSpeed commented
E2E looking better now
/lgtm
/approve

2024-02-12 10:06 UTC, merged